name: Terraform Plan

on:
  workflow_dispatch:
  pull_request: 
    branches:
      - 'master'
permissions: write-all

jobs:
  folders:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setup-matrix.outputs.value }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Matrix
        id: setup-matrix
        run: ./script/scrip.sh
        shell: bash
