name: 'Terraform'
on:
  workflow_dispatch:
    inputs:
      TFAction:
        description: "Terraform Action- Apply or Destroy"     
        required: true
        default: "apply"
permissions:
  contents: read
jobs:
  updatedfolders:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setup-m.outputs.value }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: CreateMatrix
        id: setup-m
        run: |
          bash ./script/script.sh
        shell: bash
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: dev
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_NAME }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_SECRET_KEY }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUSCRIPTION }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT }}
      TerraformBackendStorageAccount: githubactionsjorge
      TerraformBackendResourceGroup: devops-test
      TerraformBackendStorageContainer: test
      ARM_SKIP_PROVIDER_REGISTRATION: "true"    
      
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Terraform Init
      run:  |
        echo carpetas a modificar ${{ steps.setup-m.outputs.value }}
        cd ${{ steps.setup-m.outputs.value }}
        ls
        terraform init -backend-config=storage_account_name=$TerraformBackendStorageAccount -backend-config=container_name=$TerraformBackendStorageContainer -backend-config=key=dev.tfstate -backend-config=resource_group_name=$TerraformBackendResourceGroup -backend-config=subscription_id="$ARM_SUBSCRIPTION_ID" -backend-config=tenant_id="$ARM_TENANT_ID" -backend-config=client_id="$ARM_CLIENT_ID" -backend-config=client_secret="$ARM_CLIENT_SECRET"
    - name: Terraform Plan
      run:  |
        cd ${{ steps.setup-m.outputs.value }}
        terraform plan -out=plan.tfplan -input=false
    - name: Terraform Apply
      if: ${{ inputs.TFAction == 'apply'}}  
      run: |
        cd ${{ steps.setup-m.outputs.value }}
        terraform apply -input=false -auto-approve plan.tfplan
    - name: Terraform Destroy
      if: ${{ inputs.TFAction == 'destroy' }} 
      run: |
        cd ${{ steps.setup-m.outputs.value }}
        terraform destroy -input=false -auto-approve